version: 'v1'

services:
  redis:
    image: redis/redis-stack:latest
    restart: always
    ports:
      - 6379:6379
      - 8001:8001
    volumes: 
      - ./data:/data
  
  tailwind:
    build:
      context: .
      dockerfile: Dockerfile
    restart: "unless-stopped"
    command: "python manage.py tailwind start"
    tty: true

  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
      - tailwind
    ports: 
      - 8000:8000
    command: /bin/sh -c "python3 manage.py runserver 0.0.0.0:8000"
networks:
  demo_chatbot:
    driver: bridge

