# Generated by Django 4.1.2 on 2024-04-28 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 28, 9, 4, 45, 161092, tzinfo=datetime.timezone.utc)),
        ),
    ]
